const fallbackCategories=[['نسائي','👗',''],['رجالي','👔',''],['أطفال','🧒',''],['مستلزمات أطفال','🍼',''],['ألعاب','🧸',''],['قصص أطفال','📚',''],['عطور','🌸',''],['إكسسوارات','💍',''],['حقائب وأحذية','👜',''],['منزلي','🏠',''],['معدات','🧰',''],['عروض','🏷️','']];
const savedCats=window.NOUJOUD_CATALOG.categories||[];
const defaults=[['فستان نسائي أنيق','نسائي',39,'👗','جديد'],['قميص رجالي كاجوال','رجالي',25,'👔','جديد'],['طقم أطفال لطيف','أطفال',22,'🧒','جديد'],['طقم مستلزمات أطفال','مستلزمات أطفال',30,'🍼','جديد'],['دمية أطفال','ألعاب',15,'🧸',''],['قصة الأمير الصغير','قصص أطفال',8,'📚',''],['عطر NOUJOUD','عطور',35,'🌸','مميز'],['سوار أنيق','إكسسوارات',12,'💍',''],['حقيبة نسائية','حقائب وأحذية',29,'👜',''],['طقم منزلي','منزلي',24,'🏠',''],['عدة منزلية','معدات',45,'🧰',''],['فستان عرض خاص','عروض',19,'👗','خصم']];
const cartKey='noujoud_cart_v1',wishKey='noujoud_wish_v1';
let selectedLocation={lat:null,lng:null};
let products=[], categories=[], deliveryZones=[], active='الكل';
let cart=JSON.parse(localStorage.getItem(cartKey)||'[]'),wishlist=new Set(JSON.parse(localStorage.getItem(wishKey)||'[]'));
const nav=document.getElementById('nav'),cats=document.getElementById('categories'),list=document.getElementById('products');
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderNavigation(){
  const all=[['الكل','✨','']].concat(categories.map(c=>[c.name,c.emoji||'🛍️',c.image||'']));
  nav.innerHTML=all.map(c=>`<button onclick="showCategory('${esc(c[0])}')" data-cat="${esc(c[0])}">${esc(c[0])}</button>`).join('');
  cats.innerHTML=categories.map(c=>`<div class="cat" onclick="showCategory('${esc(c.name)}')"><div class="cat-icon">${c.image?`<img src="${c.image}" alt="">`:esc(c.emoji||'🛍️')}</div><b>${esc(c.name)}</b></div>`).join('');
}
async function bootCatalog(){
  await NoujoudDB.seed(window.NOUJOUD_CATALOG||{});
  products=await NoujoudDB.all('products');
  categories=await NoujoudDB.all('categories');
  deliveryZones=await NoujoudDB.all('deliveryZones');
  if(!categories.length) categories=(savedCats.length?savedCats:fallbackCategories.map((x,i)=>({id:'c'+i,name:x[0],emoji:x[1],image:x[2]})));
  if(!deliveryZones.length) deliveryZones=[{id:'z1',name:'بيروت',fee:3},{id:'z2',name:'ضواحي بيروت',fee:4},{id:'z3',name:'جبل لبنان',fee:5},{id:'z4',name:'باقي لبنان',fee:7}];
  if(!products.length && defaults.length){
    products=defaults.map((x,i)=>({id:'d'+i,name:x[0],cat:x[1],price:x[2],emoji:x[3],badge:x[4],stock:10,size:'',color:'',desc:'',image:''}));
    await NoujoudDB.putMany('products',products);
  }
  renderNavigation(); renderDeliveryZones(); render(); updateCart();
  showCategory('الكل');
}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderDeliveryZones(){
  const el=document.getElementById('deliveryZone');
  if(!el)return;
  el.innerHTML=deliveryZones.map(z=>`<option value="${esc(z.id)}">${esc(z.name)} — $${Number(z.fee||0).toFixed(2)}</option>`).join('');
  updateDeliveryFee();
}
function updateDeliveryFee(){
  const el=document.getElementById('deliveryZone');
  const feeEl=document.getElementById('deliveryFee');
  if(!el||!feeEl)return;
  const z=deliveryZones.find(x=>x.id===el.value);
  feeEl.textContent='$'+Number(z?.fee||0).toFixed(2);
}

function showCategory(cat){active=cat;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));document.getElementById('productsTitle').textContent=cat==='الكل'?'منتجات مميزة':cat;render();document.getElementById('shop').scrollIntoView({behavior:'smooth',block:'start'})}
function render(){const q=document.getElementById('searchInput').value.trim().toLowerCase();let filtered=products.filter(p=>(active==='الكل'||p.cat===active)&&(!q||p.name.toLowerCase().includes(q)||p.cat.toLowerCase().includes(q)));const sort=document.getElementById('sortSelect')?.value||'default';if(sort==='low')filtered.sort((a,b)=>a.price-b.price);if(sort==='high')filtered.sort((a,b)=>b.price-a.price);if(sort==='name')filtered.sort((a,b)=>a.name.localeCompare(b.name,'ar'));document.getElementById('resultCount').textContent=filtered.length+' منتج';document.getElementById('empty').hidden=filtered.length!==0;list.innerHTML=filtered.map(p=>{const out=p.stock<=0;return `<article class="card" onclick="openProduct('${p.id}')"><div class="pic">${p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:(p.emoji||'🛍️')}</div>${p.badge?`<span class="badge">${esc(p.badge)}</span>`:''}<button class="heart ${wishlist.has(p.id)?'liked':''}" onclick="event.stopPropagation();toggleWish('${p.id}')">${wishlist.has(p.id)?'♥':'♡'}</button><h3>${esc(p.name)}</h3><div class="price">$${p.price}</div>${out?'<small class="out">غير متوفر حالياً</small>':`<button class="add" onclick="event.stopPropagation();addToCart('${p.id}')">أضيفي للسلة</button>`}</article>`}).join('')}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById('productModal').classList.add('open');const sizes=p.size?p.size.split(',').map(x=>x.trim()).filter(Boolean):[];const colors=p.color?p.color.split(',').map(x=>x.trim()).filter(Boolean):[];document.getElementById('modalContent').innerHTML=`<div class="modal-img">${p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:p.emoji||'🛍️'}</div><div><span class="badge">${esc(p.badge||p.cat)}</span><h2>${esc(p.name)}</h2><div class="modal-price">$${p.price}</div><p>${esc(p.desc||'منتج من مجموعة NOUJOUD. تواصلي معنا لمعرفة التفاصيل والتوفر.')}</p>${sizes.length?`<label class="choice-label">المقاس<select id="modalSize">${sizes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}${colors.length?`<label class="choice-label">اللون<select id="modalColor">${colors.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`:''}<p><b>التوفر:</b> ${p.stock>0?`متوفر (${p.stock})`:'غير متوفر'}</p>${p.stock>0?`<label class="choice-label">الكمية<input id="modalQty" type="number" min="1" max="${p.stock}" value="1"></label><div class="modal-actions"><button class="primary" onclick="addModalToCart('${p.id}');closeProduct()">أضيفي للسلة</button><button class="whatsapp-product" onclick="orderProduct('${p.id}')">💬 اطلب عبر WhatsApp</button></div>`:`<button class="whatsapp-product full" onclick="orderProduct('${p.id}')">💬 اسألي نجود عن التوفر</button>`}</div>`}

function addModalToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return toast('المنتج غير متوفر');let qty=Math.max(1,Math.min(p.stock,Number(document.getElementById('modalQty')?.value||1)));let found=cart.find(x=>x.id===id);if(found){if(found.q+qty>p.stock)return toast('الكمية المطلوبة أكبر من المخزون');found.q+=qty}else cart.push({id,q:qty,size:document.getElementById('modalSize')?.value||'',color:document.getElementById('modalColor')?.value||''});saveCart();updateCart();toast('تمت إضافة الكمية إلى السلة 🛒')}
function closeProduct(){document.getElementById('productModal').classList.remove('open')}
function orderProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const size=document.getElementById('modalSize')?.value||'';const color=document.getElementById('modalColor')?.value||'';let msg=`مرحباً نجود 🌸\nأريد طلب/الاستفسار عن: ${p.name}\nالسعر: $${p.price}`;if(size)msg+=`\nالمقاس: ${size}`;if(color)msg+=`\nاللون: ${color}`;msg+='\n\nالرجاء تأكيد التوفر والتفاصيل.';window.open(`https://wa.me/96176304775?text=${encodeURIComponent(msg)}`,'_blank')}

function toggleWish(id){wishlist.has(id)?wishlist.delete(id):wishlist.add(id);localStorage.setItem(wishKey,JSON.stringify([...wishlist]));render();toast(wishlist.has(id)?'تمت الإضافة للمفضلة ❤️':'تم الحذف من المفضلة')}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<=0)return toast('المنتج غير متوفر');const found=cart.find(x=>x.id===id);if(found){if(found.q>=p.stock)return toast('لا توجد كمية إضافية');found.q++}else cart.push({id,q:1,size:'',color:''});saveCart();updateCart();toast('تمت إضافة المنتج إلى السلة 🛒')}
function saveCart(){localStorage.setItem(cartKey,JSON.stringify(cart))}function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.q,0);document.getElementById('cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(y=>y.id===x.id);return p?`<div class="cart-row"><div class="mini">${p.image?`<img src="${p.image}">`:p.emoji}</div><div class="cart-info"><b>${esc(p.name)}</b><div class="qty"><button onclick="changeQty('${x.id}',-1)">−</button>${x.q}<button onclick="changeQty('${x.id}',1)">+</button></div></div><strong>$${p.price*x.q}</strong><button class="remove" onclick="removeItem('${x.id}')">حذف</button></div>`:''}).join(''):'<div class="empty">السلة فارغة حالياً 🛍️</div>';document.getElementById('cartTotal').textContent='$'+cart.reduce((a,x)=>{const p=products.find(y=>y.id===x.id);return a+(p?p.price*x.q:0)},0)}
function changeQty(id,d){const x=cart.find(x=>x.id===id),p=products.find(y=>y.id===id);if(!x||!p)return;x.q+=d;if(x.q<=0)cart=cart.filter(y=>y.id!==id);if(x.q>p.stock)x.q=p.stock;saveCart();updateCart()}function removeItem(id){cart=cart.filter(x=>x.id!==id);saveCart();updateCart()}
function openCart(){document.getElementById('drawer').classList.add('open');updateCart()}function closeCart(){document.getElementById('drawer').classList.remove('open')}
function checkout(){if(!cart.length)return toast('السلة فارغة');document.getElementById('checkoutModal').classList.add('open')}
function sendOrder(){const name=document.getElementById('customerName').value.trim(),phone=document.getElementById('customerPhone').value.trim(),address=document.getElementById('customerAddress').value.trim(),zoneId=document.getElementById('deliveryZone')?.value||'',zone=deliveryZones.find(z=>z.id===zoneId),deliveryFee=Number(zone?.fee||0);if(!name||!phone||!address)return toast('عبّي الاسم، الهاتف والعنوان');const items=cart.map(x=>{const p=products.find(y=>y.id===x.id);return {name:p.name,qty:x.q,price:p.price,size:x.size||'',color:x.color||''}});const subtotal=items.reduce((a,x)=>a+x.price*x.qty,0),total=subtotal+deliveryFee;const lines=items.map(x=>`${x.name}${x.size?' · المقاس: '+x.size:''}${x.color?' · اللون: '+x.color:''} × ${x.qty} = $${x.price*x.qty}`).join('\n');const msg=`مرحباً نجود 🌸\nأريد تأكيد هذا الطلب:\n${lines}\n\nالمجموع قبل التوصيل: $${subtotal.toFixed(2)}\nمنطقة التوصيل: ${zone?.name||'غير محددة'}\nكلفة التوصيل: $${deliveryFee.toFixed(2)}\nالمجموع النهائي: $${total.toFixed(2)}\nالاسم: ${name}\nالهاتف: ${phone}\nالعنوان: ${address}${selectedLocation.lat&&selectedLocation.lng?'\nموقعي على الخريطة: https://www.google.com/maps?q='+selectedLocation.lat+','+selectedLocation.lng:''}`;window.open(`https://wa.me/96176304775?text=${encodeURIComponent(msg)}`,'_blank');cart=[];saveCart();updateCart();document.getElementById('checkoutModal').classList.remove('open');document.getElementById('drawer').classList.remove('open');toast('تأكدي من الضغط على إرسال داخل WhatsApp لإتمام الطلب')}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
document.getElementById('cartBtn').onclick=openCart;
document.getElementById('drawer').onclick=e=>{if(e.target.id==='drawer')closeCart()};document.getElementById('productModal').onclick=e=>{if(e.target.id==='productModal')closeProduct()};document.getElementById('checkoutModal').onclick=e=>{if(e.target.id==='checkoutModal')e.target.classList.remove('open')};document.getElementById('searchInput').addEventListener('input',render);document.getElementById('sortSelect')?.addEventListener('change',render);document.getElementById('wishlistBtn').onclick=()=>{active='الكل';const arr=products.filter(p=>wishlist.has(p.id));document.getElementById('productsTitle').textContent='المفضلة ❤️';list.innerHTML=arr.map(p=>`<article class="card" onclick="openProduct('${p.id}')"><div class="pic">${p.image?`<img src="${p.image}">`:p.emoji}</div><h3>${esc(p.name)}</h3><div class="price">$${p.price}</div><button class="add" onclick="event.stopPropagation();addToCart('${p.id}')">أضيفي للسلة</button></article>`).join('')||'<div class="empty">ما في منتجات بالمفضلة بعد.</div>';document.getElementById('shop').scrollIntoView({behavior:'smooth'})};bootCatalog().catch(e=>{console.error(e);toast('تعذر تحميل المنتجات')});
